services:
  php:
    container_name: php
    build: docker/
    restart: always
    working_dir: /app
    volumes:
      - "./:/app"
      - "./docker/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"
    environment:
      XDEBUG_MODE: "coverage"
    networks:
      - php

volumes:
  db-data:

networks:
  php: